name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - seaborn
  - scikit-learn 
  - keras 
  - tensorflow
  - numpy
  - pandas
  - geopy
  - folium
  - openpyxl